      {
         "vice_resid_volume_6581",
         "Audio > ReSID 6581 Volume",
         "",
         {
            { "0", NULL },
            { "5", NULL },
            { "10", NULL },
            { "15", NULL },
            { "20", NULL },
            { "25", NULL },
            { "30", NULL },
            { "35", NULL },
            { "40", NULL },
            { "45", NULL },
            { "50", NULL },
            { "55", NULL },
            { "60", NULL },
            { "65", NULL },
            { "70", NULL },
            { "75", NULL },
            { "80", NULL },
            { "85", NULL },
            { "90", NULL },
            { "95", NULL },
            { "100", NULL },
            { "105", NULL },
            { "110", NULL },
            { "115", NULL },
            { "120", NULL },
            { "125", NULL },
            { "130", NULL },
            { "135", NULL },
            { "140", NULL },
            { "145", NULL },
            { "150", NULL },
            { "155", NULL },
            { "160", NULL },
            { "165", NULL },
            { "170", NULL },
            { "175", NULL },
            { "180", NULL },
            { "185", NULL },
            { "190", NULL },
            { "195", NULL },
            { "200", NULL },
            { "205", NULL },
            { "210", NULL },
            { "215", NULL },
            { "220", NULL },
            { "225", NULL },
            { "230", NULL },
            { "235", NULL },
            { "240", NULL },
            { "245", NULL },
            { "250", NULL },
            { "255", NULL },
            { "260", NULL },
            { "265", NULL },
            { "270", NULL },
            { "275", NULL },
            { "280", NULL },
            { "285", NULL },
            { "290", NULL },
            { "295", NULL },
            { "300", NULL },
            { NULL, NULL },
         },
         "100"
      },
      {
         "vice_resid_volume_8580",
         "Audio > ReSID 8580 Volume",
         "",
         {
            { "0", NULL },
            { "5", NULL },
            { "10", NULL },
            { "15", NULL },
            { "20", NULL },
            { "25", NULL },
            { "30", NULL },
            { "35", NULL },
            { "40", NULL },
            { "45", NULL },
            { "50", NULL },
            { "55", NULL },
            { "60", NULL },
            { "65", NULL },
            { "70", NULL },
            { "75", NULL },
            { "80", NULL },
            { "85", NULL },
            { "90", NULL },
            { "95", NULL },
            { "100", NULL },
            { "105", NULL },
            { "110", NULL },
            { "115", NULL },
            { "120", NULL },
            { "125", NULL },
            { "130", NULL },
            { "135", NULL },
            { "140", NULL },
            { "145", NULL },
            { "150", NULL },
            { "155", NULL },
            { "160", NULL },
            { "165", NULL },
            { "170", NULL },
            { "175", NULL },
            { "180", NULL },
            { "185", NULL },
            { "190", NULL },
            { "195", NULL },
            { "200", NULL },
            { "205", NULL },
            { "210", NULL },
            { "215", NULL },
            { "220", NULL },
            { "225", NULL },
            { "230", NULL },
            { "235", NULL },
            { "240", NULL },
            { "245", NULL },
            { "250", NULL },
            { "255", NULL },
            { "260", NULL },
            { "265", NULL },
            { "270", NULL },
            { "275", NULL },
            { "280", NULL },
            { "285", NULL },
            { "290", NULL },
            { "295", NULL },
            { "300", NULL },
            { NULL, NULL },
         },
         "100"
      },
